routes/index.js

database is now spelled correctly.
close #1

fix spelling error

---

models/db.js

changes db name to nota

---

Readme.md

update readme on new node installation instructions

---

package.json
scripts/production.sh
test/test.js

This pull request contains unit tests on carrying out certain successful actions.
related to #16

add unit test for successful actions

---

test/test.js

additional unit tests

---

test/test.js

this add test cases for registration and login
related to #16
close #26

add test cases specific to user actions

---

config/development.js
routes/users.js
scripts/development.sh

This pull request adds a development script for local testing.
Related to issue #40

Implement development script

---

postman/Nota.postman-2.1_collection.json
postman/Nota.postman-2.1_environment.json

This pull request adds the ability for someone to import the collection and environment into postman for easy testing
close #42

Add postman collection and environment for local

---

Readme.md

This pull request allows the screenshots and gifs to be loaded in the readme
close #45

Link screenshots in readme

---

Readme.md

adds improved instructions for installing mongo db

---

Readme.md

Instructions informing the user that they should be running ubuntu 16.04 to get Nota running.
close #64

clarifies to the user to use ubuntu 16.04

---

Readme.md

Allow users to get quickly setup with the vagrantfile I worked on.
close #66

add vagrantfile link for nota

---

package-lock.json
package.json

After manually starting the build in travis, builds are passing. We shall monitor if issues of this version arises in the future. Related to issue #70 
close #70

Greenkeeper/coveralls 3.0.3

---

.gitignore
.travis.yml
app.js
bin/www
docker-compose.yml
models/db.js
test/test.js

Nota will now wait and attempt to connect to the database. After 5 failed attempts, the app will shutdown.
related to #75 
close #75

Prevent Nota from starting before verifying database connection.

---

.eslintignore
.eslintrc.js
.travis.yml
app.js
bin/www
config/default.js
config/development.js
config/production.js
config/test.js
models/db.js
models/sessions.js
models/tasks.js
models/users.js
package-lock.json
package.json
routes/index.js
routes/users.js
services/mailgun.js
services/sessions.js
test/clean/drop_db.js
test/test.js

This PR adds the implementation to us eslint to format and check for code errors of Nota.
Run this command `./node_modules/.bin/eslint ../*` and/or install an eslint plugin for your text editor to see which files are breaking the rules
related to #38 
close #38

Adds eslint and resulting refactoring of code

---

Readme.md
package-lock.json
package.json

Greenkeeper/eslint 6.2.2

---

package-lock.json
package.json

Greenkeeper/mongodb 3.3.0

---

.github/workflows/eslint.yaml

This PR adds a GitHub workflow to run eslint.
We shall see if the changes here works.

Test GitHub action integration

---

.github/workflows/eslint.yaml

Revert "Revert "Test GitHub action integration""

---

Dockerfile
models/db.js
package-lock.json
routes/users.js

This PR consist of changes that allows Nota to run on node v8.
This issue is related to #101 
This PR does not contain any changes on including `npm ci` by the last commit.

Upgrade node to v8

---

Readme.md

Update the Readme.md

---

.travis.yml
Dockerfile
Dockerfile-mongodb
docker-notes.md

This PR has the Nota and Mongodb images pull our specific ubuntu image from Dockerhub. This reduces build and testing time.
A new issue will be created to build the ubuntu image using a cron job with GitHub actions.
Issue #109 
close #109

Pull our specific Ubuntu image from DockerHub

---

scripts/travis-deploy.sh

This PR fixes the command that tags the deployment image and adds `sudo` for the docker push command
This PR is related to issue #113

fix docker push command & tagging for CD w/ travis

---

.travis.yml

fix production branch name in travis

---

.travis.yml
package-lock.json
scripts/travis-deploy.sh

This PR merges the changes found in the following PRs, #121 #119

Merge master into production

---

Dockerfile

This PR allows a non-root user to be created and be used for running nota.
This issue is related to issue #123 
close #123

chore(docker): replace default user

---

Dockerfile
Readme.md
docker-notes.md
scripts/development.sh

This PR updates the Readme file to reflect the Docker workflow we are now using for testing, development, and for production. This PR also contains a change to `Dockerfile` to fix a permissions issue and `./scripts/development.sh` to use the correct database uri.
This PR is related to issue #129 and #127

fix(chores): fix user permissions in docker, uri in development script, and update readme.md

---

Readme.md

docs(docker): replace no docker with without docker

---

Readme.md

Project has been migrated from Travis-ci.org to Travis-ci.com. This includes the updated badge. I also added a badge using https://shields.io/ for Snyk.
This PR is related to issue #153 
close #153

doc(readme): add snyk badge and update travis-ci badge

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/generic-issue.md

Update issue templates

---

CONTRIBUTING.md

This PR adds `CONTRIBUTING.md` file for the project.
close #169

docs(contributing.md): create CONTRIBUTING.md

---

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md

This PR provides a default PR template so that users know what to provide when making a PR.
This PR is related to #171 
close #171

docs(template): provide a default pr template

---

app.js

This PR refactors how the Mongoose schema is initialized in `app.js`.
N/A
The changes have been tested locally.
This PR is related to issue #225 
close #225

refactor(mongoose): modify app.js to better define and use schema models

---

Dockerfile
package-lock.json
package.json

This PR updates the dependencies in Nota by running `npm audit fix --force`. The `dockerfile` was also modified with some improvements and to fix failing builds within Travis-CI.
N/A
The changes in this PR were tested with Travis-CI and locally with `docker-compose build` and then `docker-compose up --exit-code-from nota`.
This PR is related to issue #253

fix(dependencies): upgrade applicable dependencies by running npm audit fix --force

---

routes/users.js
services/sessions.js

This PR implements changes to prevent malicious queries from user-controlled data being sent to the database.
Referred to https://docs.mongodb.com/manual/reference/operator/query/eq/#security-implications.
Changes were tested by running `./scripts/test.sh`
This PR is related to issue #283 
close #283

fix(queries): implement $eq operator to reduce potential malicious queries from user controlled data

---

package-lock.json
package.json

This PR updates `package.json` and `package-lock.json` to installed updated dependencies to resolve some vulnerabilities.
PRs and issues will be closed that are resolved with this PR. View them below.
Tests are passing when running `./scripts/test.sh` / `sudo docker-compose up --exit-code-from nota`
close #326
close #323
close #319 
close #312

fix(dependencies): update dependencies to resolve a portion of known security vulnerabilities

---

package-lock.json
package.json
test/test.js

This PR replaces axios with supertest for our testing. Supertest makes it easier to write and maintain the integration tests.
N/A
The changes in this PR have been tested by running the mocha tests.
This PR is related to #334 
close #334

tests(supertest): replace axios with supertest for the integration tests
